[tool.poetry]
name = "pyzelda"
version = "0.1.0"
description = "Simple top down game"
authors = ["slottwo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
